version: '3.9'

services:
  bot:
    container_name: tgapp2011
    image: tgapp2011:latest
    build: .
    environment:
      - TZ=Europe/Moscow
      - DB_URL=postgresql+psycopg://postgres:123123@bot_database:5432/postgres
    depends_on:
      - tgapp2011_database

    restart: always
  tgapp2011_database:
    container_name: tgapp2011_database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ=Europe/Moscow
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}

